version: "3.1"

services:
  db:
    container_name: mysql-server-1
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: risknetwork
    volumes:
      - 'D:/Nigel/Dropbox/MyApps/RiskNetwork/data:/var/lib/mysql'

  rstudio:
    container_name: rstudiotidy
    image: rocker/tidyverse
    ports:
      - '8787:8787'
    environment:
      PASSWORD: example
